from pathlib import Path
from uuid import UUID, uuid4
from fastapi import UploadFile
from typing import Optional
from src.app.config import settings
import structlog
import os
from datetime import datetime

logger = structlog.get_logger()


class FileService:
    """文件服务类"""
    
    def __init__(self):
        self.storage_type = settings.STORAGE_TYPE
        self.local_path = Path(settings.STORAGE_LOCAL_PATH)
        self.local_path.mkdir(exist_ok=True, parents=True)
    
    async def upload_file(self, file: UploadFile, user_id: str) -> dict:
        """
        上传文件
        """
        if self.storage_type == "local":
            return await self._upload_local(file, user_id)
        else:
            # TODO: 实现其他存储方式（S3/OSS等）
            raise NotImplementedError(f"Storage type {self.storage_type} not implemented")
    
    async def _upload_local(self, file: UploadFile, user_id: str) -> dict:
        """
        本地上传文件
        """
        # 生成文件名
        file_extension = Path(file.filename).suffix if file.filename else ""
        file_id = str(uuid4())
        stored_filename = f"{file_id}{file_extension}"
        
        # 创建用户目录
        user_dir = self.local_path / user_id
        user_dir.mkdir(exist_ok=True)
        
        file_path = user_dir / stored_filename
        
        # 保存文件
        content = await file.read()
        with open(file_path, "wb") as f:
            f.write(content)
        
        file_size = os.path.getsize(file_path)
        
        logger.info(
            "file_uploaded",
            file_id=file_id,
            original_name=file.filename,
            size=file_size,
            user_id=user_id,
            content_type=file.content_type
        )
        
        return {
            "id": file_id,
            "filename": stored_filename,
            "original_name": file.filename,
            "size": file_size,
            "mime_type": file.content_type,
            "url": f"/uploads/{user_id}/{stored_filename}",
            "created_at": datetime.utcnow().isoformat()
        }
    
    async def get_file_path(self, file_id: str, user_id: Optional[str] = None) -> Optional[Path]:
        """
        获取文件路径
        """
        if self.storage_type != "local" or not user_id:
            return None

        # IDs are UUIDs generated by the service, never glob patterns or paths.
        try:
            safe_file_id = str(UUID(file_id))
            safe_user_id = str(UUID(user_id))
        except (ValueError, TypeError, AttributeError):
            return None

        root = self.local_path.resolve()
        user_dir = (root / safe_user_id).resolve()
        if user_dir.parent != root:
            return None
        for file_path in user_dir.glob(f"{safe_file_id}.*"):
            resolved = file_path.resolve()
            if resolved.parent == user_dir and resolved.is_file():
                return resolved
        
        return None
    
    async def delete_file(self, file_id: str, user_id: str) -> bool:
        """
        删除文件
        """
        file_path = await self.get_file_path(file_id, user_id)
        if file_path and file_path.exists():
            file_path.unlink()
            logger.info(
                "file_deleted",
                file_id=file_id,
                user_id=user_id
            )
            return True
        
        return False
